amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: scan
    robot_model_type: differential
    odom_topic: odom
    laser_max_range: 30.0

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/PurePursuitController"

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names: ["nav2_compute_path_to_pose_action_bt_node",
                      "nav2_follow_path_action_bt_node"]

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    plugin_lib_names: ["nav2_waypoint_follower/WaypointFollower"]

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: map.yaml

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    plugin_lib_names: ["nav2_recoveries/Spin",
                      "nav2_recoveries/BackUp",
                      "nav2_recoveries/Wait"]

local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: scan
      scan:
        topic: scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: LaserScan
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true

global_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: map
    robot_base_frame: base_link
    rolling_window: false
    width: 10.0
    height: 10.0
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true
      subscribe_to_updates: true
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: scan
      scan:
        topic: scan
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: LaserScan
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
