slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_toolbox:
      plugin: "slam_toolbox"
      map_frame: map
      base_frame: base_link
      odom_frame: odom
      update_map: true
      publish_static_map: false
      max_laser_range: 20.0
      minimum_time_interval: 0.5
